{% set name = "lefthook" %}
{% set version = "1.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v{{ version }}.tar.gz
  sha256: d98b5b93f40ef72facb67c2ec119dfcd5dfc4eb49f7c081ab7a333508bd45e08

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - lefthook --help

about:
  home: https://github.com/evilmartians/lefthook
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  dev_url: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
