{% set name = "lefthook" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v{{ version }}.tar.gz
  sha256: 59527d3ffcf75c836efedf52657aa2a76c3b0b0db87a89d6db801f87819873c8

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - lefthook --help

about:
  home: https://github.com/evilmartians/lefthook
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  dev_url: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
