{% set name = "lefthook" %}
{% set version = "1.11.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v{{ version }}.tar.gz
  sha256: c5e4b1d24fa700bec2f3c1ac5332ff2c55db76a8a13b26783fa72f6ea4970370

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - lefthook --help

about:
  home: https://github.com/evilmartians/lefthook
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  dev_url: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
