{% set name = "lefthook" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v{{ version }}.tar.gz
  sha256: e8e49bc5796f7cd035379cdb7df6afd335ee5687e6a6d4377a793e4fdc1cf467

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - lefthook --help

about:
  home: https://github.com/evilmartians/lefthook
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  dev_url: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
