schema_version: 1

context:
  name: lefthook
  version: "1.13.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v${{ version }}.tar.gz
  sha256: 4f610a4ab9622d7073f3f11e315ec62e6c24aca3778904937b7c8e6beb893f7b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - lefthook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  homepage: https://github.com/evilmartians/lefthook
  repository: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
