schema_version: 1

context:
  name: lefthook
  version: "2.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v${{ version }}.tar.gz
  sha256: 5d152b84e6a1aecd1d3173865a69f0466d1c166c3978ce6e679293194973b845

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - lefthook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  homepage: https://github.com/evilmartians/lefthook
  repository: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
