schema_version: 1

context:
  name: lefthook
  version: "2.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v${{ version }}.tar.gz
  sha256: d23c05f0ce9825888fa088c5a27610e8d08043fc0c0682de170585f29644afbb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - lefthook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  homepage: https://github.com/evilmartians/lefthook
  repository: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
