schema_version: 1

context:
  name: lefthook
  version: 1.11.16

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v${{ version }}.tar.gz
  sha256: aa99bca23b9d840d8f465adf402d6dffadea6d84409e1342b6629eb995d36338

build:
  number: 1

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - lefthook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  homepage: https://github.com/evilmartians/lefthook
  repository: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
