schema_version: 1

context:
  name: lefthook
  version: "2.0.13"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/evilmartians/lefthook/archive/v${{ version }}.tar.gz
  sha256: 6c05c91b14ab541e65c7ed853ec1540e1aa2c2afeb61ac6e85001f6c2d0a3e10

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - lefthook --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast and powerful Git hooks manager for any type of projects
  homepage: https://github.com/evilmartians/lefthook
  repository: https://github.com/evilmartians/lefthook

extra:
  recipe-maintainers:
    - danielnachun
    - pavelzw
